### ISSUE TITLE
你好，关于花呗更换银行卡这个例子的相似度，结果有差别

### ISSUE THREAD

**Issue by yhf2lj** [shibing624/simtext#2]
你的readme上相似度是0.9569100456524151

我本地计算的结果是0.784770996149448

请问你是在此此包的基础上额外做了深层语义相似度吗

相关：
```
import simtext

a = '如何更换花呗绑定银行卡'
b = '花呗更改绑定银行卡'
s = simtext.score(a, b)
print(s)
```
output:

`0.9569100456524151`

**Comment by shibing624** [comment]
更新一下版本

**Comment by yhf2lj** [comment]
> 更新一下版本

今早刚安装的，以及刚刚更新过一次，依然是这样，是不是我们使用的词向量不一样，我使用的是自动下载的词向量

**Comment by shibing624** [comment]
开发版，还未发布到pip。新版本v1.4本周内测试后会发布到pip。

**Comment by shibing624** [comment]
> > 更新一下版本
> 
> 今早刚安装的，以及刚刚更新过一次，依然是这样，是不是我们使用的词向量不一样，我使用的是自动下载的词向量

是，新版本调用腾讯发布的词向量（轻量版）

**Comment by yhf2lj** [comment]
> > > 更新一下版本
> > 
> > 
> > 今早刚安装的，以及刚刚更新过一次，依然是这样，是不是我们使用的词向量不一样，我使用的是自动下载的词向量
> 
> 是，新版本调用腾讯发布的词向量（轻量版）

谢谢指导，正在更新github下载的版本，

话说 **深度语义匹配模型** 的功能以后会加入进去吗？

**Comment by shibing624** [comment]
see matchzoo. 本项目会新增一个fine-tuned 的bert相似度计算模型

**Comment by yhf2lj** [comment]
> see matchzoo. 本项目会新增一个fine-tuned 的bert相似度计算模型

请问一下，新模型中，执行predict.py 报错
Traceback (most recent call last):
  File "/mnt/c/Users/DEMON/Desktop/simtext-master/simtext/bert/predict.py", line 11, in <module>
    from simtext.bert.model import BertSimilarity
  File "/mnt/c/Users/DEMON/Desktop/simtext-master/simtext/bert/model.py", line 16, in <module>
    from simtext.bert import optimization
  File "/mnt/c/Users/DEMON/Desktop/simtext-master/simtext/bert/optimization.py", line 85, in <module>
    class AdamWeightDecayOptimizer(tf.train.Optimizer):
AttributeError: module 'tensorflow_core._api.v2.train' has no attribute 'Optimizer'

然后我搜索了一下，更换成了 tf.keras.optimizers
但是依然出错，因此，想请教一下你使用的tensorflow版本，因为我没有在requirment.txt看到关于tensorflow版本的依赖说明

**Comment by shibing624** [comment]
keras-bert>=0.80.0
tensorflow>=1.14.0
